---
name: 🐛 Bug Report
description: Report a bug or issue with SuperClaude
title: "[Bug] "
labels: ["type/bug", "status/needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide detailed information to help us fix it.
        
        **Before submitting:** Please check our [Discussions Q&A](../../discussions/categories/q-a) for similar issues.
        
        **Community Guidelines:** Follow our [evidence-based approach](../blob/latest/docs/DISCUSSIONS_WELCOME.md) - provide specific details and testing results.

  - type: input
    id: superclaude-version
    attributes:
      label: SuperClaude Version
      description: What version of SuperClaude are you using?
      placeholder: v2.0.1
    validations:
      required: true

  - type: input
    id: claude-code-version
    attributes:
      label: Claude Code Version
      description: What version of Claude Code are you using?
      placeholder: 0.20.0 (or your version)
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux (Ubuntu)
        - Linux (Other)
        - WSL (Windows Subsystem for Linux)
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install SuperClaude: ./install.sh
        2. Run command: /analyze --code --persona-architect
        3. Open file example.py
        4. See error message...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Command should analyze code and provide architectural insights...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Command failed with error message or unexpected behavior...
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Include any error messages or logs
      placeholder: |
        ```
        [ERROR] SuperClaude: Command failed
        Error: Cannot find .claude directory...
        ```
        
        💡 **Tip**: Include the full error message and any relevant log output.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots of the error
        - Your .claude/settings.local.json (remove sensitive data)
        - Output of: ./install.sh --version
        - Any custom configurations or MCP server settings
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues and discussions
          required: true
        - label: I have provided all required information
          required: true
        - label: I can reproduce this issue consistently
          required: false
        - label: I have read the community guidelines
          required: true
